export const gestureData = [
  { name: "Call", value: "call" },
  { name: "Dislike", value: "dislike" },
  { name: "Fist", value: "fist" },
  { name: "Four", value: "four" },
  { name: "Like", value: "like" },
  { name: "Mute", value: "mute" },
  { name: "OK", value: "ok" },
  { name: "One", value: "one" },
  { name: "Palm", value: "palm" },
  { name: "Peace", value: "peace" },
  { name: "Peace Inv.", value: "peace inv." },
  { name: "Rock", value: "rock" },
  { name: "Stop", value: "stop" },
  { name: "Stop Inv.", value: "stop inv." },
  { name: "Three", value: "three" },
  { name: "Three 2", value: "three 2" },
  { name: "Two Up", value: "two up" },
  { name: "Two Up Inv.", value: "two up inv." },
];
